TRUNCATE TABLE book RESTART IDENTITY CASCADE;

INSERT INTO book (title, author, slug, genre, description) VALUES
                                                               ('The Metamorphosis', 'Franz Kafka', 'the-metamorphosis', 'Existentialism', 'A haunting exploration of isolation and transformation.'),
                                                               ('Norwegian Wood', 'Haruki Murakami', 'norwegian-wood', 'Romantic Realism', 'Memory, music, and melancholic longing.'),
                                                               ('1984', 'George Orwell', '1984', 'Dystopian', 'A chilling vision of a totalitarian future.'),
                                                               ('Brave New World', 'Aldous Huxley', 'brave-new-world', 'Science Fiction', 'A utopia gone wrong.'),
                                                               ('The Stranger', 'Albert Camus', 'the-stranger', 'Existentialism', 'Absurdism and emotional detachment in an indifferent world.'),
                                                               ('Siddhartha', 'Hermann Hesse', 'siddhartha', 'Philosophical Fiction', 'A spiritual journey of self-discovery.'),
                                                               ('Crime and Punishment', 'Fyodor Dostoevsky', 'crime-and-punishment', 'Psychological', 'Guilt and redemption in tsarist Russia.'),
                                                               ('To the Lighthouse', 'Virginia Woolf', 'to-the-lighthouse', 'Modernist', 'Time, memory, and perception.'),
                                                               ('The Trial', 'Franz Kafka', 'the-trial', 'Absurdist', 'A man arrested for a crime he doesn’t understand.'),
                                                               ('Invisible Cities', 'Italo Calvino', 'invisible-cities', 'Surrealism', 'Dreamlike tales of imagined cities.'),
                                                               ('The Bell Jar', 'Sylvia Plath', 'the-bell-jar', 'Autobiographical Fiction', 'Mental health and identity crisis.'),
                                                               ('The Unbearable Lightness of Being', 'Milan Kundera', 'unbearable-lightness', 'Philosophical Fiction', 'Freedom, love, and chance.'),
                                                               ('A Portrait of the Artist as a Young Man', 'James Joyce', 'portrait-of-the-artist', 'Modernist', 'The making of a writer.'),
                                                               ('Steppenwolf', 'Hermann Hesse', 'steppenwolf', 'Psychological', 'Man versus his inner beast.'),
                                                               ('The Book of Disquiet', 'Fernando Pessoa', 'book-of-disquiet', 'Fragmentary Fiction', 'Melancholy and introspection.'),
                                                               ('The Moth Journal', 'Various', 'moth-journal', 'Anthology', 'Poetic whispers from the void.'),
                                                               ('The Waves', 'Virginia Woolf', 'the-waves', 'Modernist', 'Multiple consciousnesses in lyrical prose.'),
                                                               ('Slaughterhouse-Five', 'Kurt Vonnegut', 'slaughterhouse-five', 'Science Fiction', 'Time travel and trauma.'),
                                                               ('The Plague', 'Albert Camus', 'the-plague', 'Allegorical Fiction', 'Existence in crisis.'),
                                                               ('Kafka on the Shore', 'Haruki Murakami', 'kafka-on-the-shore', 'Surrealist', 'A metaphysical odyssey.'),
                                                               ('Demian', 'Hermann Hesse', 'demian', 'Coming-of-Age', 'Spiritual awakening and duality.'),
                                                               ('Leaves of Grass', 'Walt Whitman', 'leaves-of-grass', 'Poetry', 'An ode to the human spirit.'),
                                                               ('No Longer Human', 'Osamu Dazai', 'no-longer-human', 'Confessional', 'Alienation and depression.'),
                                                               ('The Idiot', 'Fyodor Dostoevsky', 'the-idiot', 'Classic', 'Pure goodness misunderstood.'),
                                                               ('Zen and the Art of Motorcycle Maintenance', 'Robert Pirsig', 'zen-motorcycle', 'Philosophical Memoir', 'A journey of quality and meaning.');
