TRUNCATE TABLE review RESTART IDENTITY CASCADE;

INSERT INTO review (book_id, reviewer, content, rating, created_at) VALUES
                                                                        (1, 'Ray', 'This book altered my worldview.', 5, NOW()),
                                                                        (2, 'Luna', 'Murakami never disappoints.', 4, NOW()),
                                                                        (3, 'Kai', 'Orwell’s predictions hit too close.', 5, NOW()),
                                                                        (4, 'Mira', 'A haunting yet beautiful future.', 4, NOW()),
                                                                        (5, 'Eli', 'Made me rethink absurdism.', 5, NOW()),
                                                                        (6, 'Zane', 'A calm yet powerful journey.', 4, NOW()),
                                                                        (7, 'Ray', 'Dostoevsky is a beast.', 5, NOW()),
                                                                        (8, 'Luna', 'Woolf’s writing is hypnotic.', 4, NOW()),
                                                                        (9, 'Kai', 'Kafka’s nightmare made real.', 4, NOW()),
                                                                        (10, 'Mira', 'These cities live in my head now.', 5, NOW()),
                                                                        (11, 'Eli', 'Plath’s pain is palpable.', 5, NOW()),
                                                                        (12, 'Zane', 'A philosophy in disguise.', 4, NOW()),
                                                                        (13, 'Ray', 'Joyce was ahead of his time.', 4, NOW()),
                                                                        (14, 'Luna', 'Felt like a mirror to my inner self.', 5, NOW()),
                                                                        (15, 'Kai', 'Pessoa is raw, honest, and deep.', 5, NOW()),
                                                                        (16, 'Mira', 'Loved the fragments of emotion.', 4, NOW()),
                                                                        (17, 'Eli', 'A symphony in written form.', 5, NOW()),
                                                                        (18, 'Zane', 'Dark humor meets time travel.', 4, NOW()),
                                                                        (19, 'Ray', 'Camus with another banger.', 5, NOW()),
                                                                        (20, 'Luna', 'Murakami’s weirdness is peak.', 5, NOW()),
                                                                        (21, 'Kai', 'Hesse always hits.', 5, NOW()),
                                                                        (22, 'Mira', 'Whitman is the soul of poetry.', 5, NOW()),
                                                                        (23, 'Eli', 'This book hurt in the best way.', 5, NOW()),
                                                                        (24, 'Zane', 'Kindness is a radical act.', 5, NOW()),
                                                                        (25, 'Ray', 'Still thinking about this ride.', 5, NOW());
